keys:
        - &admin_scott age15hzqzdp289m868stvw6937hdzt3qqt0hz5uj4tqt7et5yne0s5eq7dhmgn
        - &server_bob_the_builder age1vq8w35wsdvh0fzshjaqly97knexs3cc4e6jqm7nqt3d07mdhxv4qwtm2qk
         

creation_rules:
        - key_groups:
                - age:
                        - *admin_scott
                        - *server_bob_the_builder
