platform: linux
image_resource:
  type: registry-image
  source:
    repository: mozilla/sops
    tag: alpine
inputs:
- name: source
outputs:
- name: secrets
params:
  SOPS_AGE_KEY: ((age_key))
run:
  path: sh
  args:
  - -c
  - sops --decrypt source/secrets/((secret_file)) > secrets/((secret_file))