platform: linux
image_resource:
  type: registry-image
  source:
    repository: nixpkgs/nix
    tag: nixos-22.11 # latest == nixos unstable
params:
  CACHIX_NAME: scottbot95-homelab
  NIX_CONFIG: |
    extra-experimental-features = nix-command flakes
    extra-substituters = http://nas.lan.faultymuse.com:5000
    require-sigs = false
    max-jobs = 4
    cores = 8
inputs:
- name: source
- name: secrets
caches:
- path: nix-store
run:
  path: sh
  args:
  - -ec
  - |
    mkdir -p /root/.ssh
    cat <<EOT > /root/.ssh/worker_key
    ((ssh_key))
    EOT
    chmod 600 /root/.ssh/worker_key

    set -v

    # Configure SSH
    mkdir -p /root/.ssh
    cat<<EOT > /root/.ssh/config
    Host nas.lan.faultymuse.com
        User concourse-worker
        StrictHostKeyChecking accept-new
        IdentitiesOnly yes
        IdentityFile /root/.ssh/worker_key
    EOT

    cp secrets/* source/secrets/

    cd source

    set -x +v

    nix develop -v -c sh -ex <<EOT
      cachix use $CACHIX_NAME
      cachix watch-exec $CACHIX_NAME ((command)) -- ((args))
    EOT
    
    nix copy --to ssh://nas.lan.faultymuse.com --all -v
