platform: linux
params:
  NIX_CONFIG: |
    extra-experimental-features = nix-command flakes
    max-jobs = 4
    cores = 4
inputs:
- name: source
- name: secrets
# caches:
# - path: nix-store
run:
  path: sh
  args:
  - -exc
  - |
    # echo "extra-substituters = file://$PWD/nix-store" | tee -a /etc/nix/nix.conf > /dev/null
    # echo 'require-sigs = false' | tee -a /etc/nix/nix.conf > /dev/null

    cp -v secrets/* source/secrets/
    cd source
    cachix watch-exec $CACHIX_NAME nix-shell -- --run "((command)) ((args))"

    # nix copy --to file://$PWD/nix-store --all -v
