platform: linux
image_resource:
  type: registry-image
  source:
    repository: nixpkgs/nix
    tag: nixos-22.11 # latest == nixos unstable
params:
  CACHIX_NAME: scottbot95-homelab
  NIX_CONFIG: |
    extra-experimental-features = nix-command flakes
    extra-substituters = http://nas.lan.faultymuse.com:5000
    require-sigs = false
    max-jobs = 4
    cores = 8
inputs:
- name: source
- name: secrets
caches:
- path: nix-store
run:
  path: sh
  args:
  - -evc
  - |
    # Configure SSH
    mkdir -p /root/.ssh
    cat<<EOT > /root/.ssh/config
    Host nas.lan.faultymuse.com
        User concourse-worker
        StrictHostKeyChecking accept-new
        IdentitiesOnly yes
        IdentityFile /root/.ssh/worker_key
    EOT
    chmod 600 /root/.ssh/*

    cp secrets/* source/secrets/
    cp secrets/worker_key /root/.ssh/

    cd source

    set -x +v

    nix develop -v -c sh -ex <<EOT
      echo does this even work
      # cachix use $CACHIX_NAME
      # cachix watch-exec $CACHIX_NAME ((command)) -- ((args))
    EOT

    nix develop -v -c cachix use $CACHIX_NAME
    nix develop -v -c cachix watch-exec $CACHIX_NAME ((command)) -- ((args))

    nix copy --to ssh://nas.lan.faultymuse.com --all -v
