{
 "title": "FaultyBot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Guilds In Cache",
   "type": "timeseries",
   "description": "Presumably a proxy for connected guilds with some delay",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "guilds_in_cache{instance=\"faultybot.prod.faultymuse.com:9000\", quantile=\"1\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg(gpt_response_seconds{job=\"faultybot.prod.faultymuse.com\"})",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(gpt_requests_total{job=\"faultybot.prod.faultymuse.com\"})",
     "legendFormat": "Request Count"
    },
    {
     "expr": "sum(gpt_responses_total{job=\"faultybot.prod.faultymuse.com\"})",
     "legendFormat": "Response Count"
    }
   ]
  }
 ]
}